### ISSUE TITLE
Spit out git shas for each service

### ISSUE THREAD

**Issue by fivegrant** [DARPA-ASKEM/simulation-integration#13]
Similarly to what's done with TA1, we would like to provide the version info for SciML Service, PyCIEMSS Service and TDS in the report

**Comment by mattprintz** [comment]
@fivegrant Is there a preferred endpoint/methodology for providing the sha?

**Comment by fivegrant** [comment]
@mattprintz going to have to standardize it across the services but i was thinking a GET to `/health` would return an object with whatever properties you'd like as long as there is a property called `git_sha`

**Comment by fivegrant** [comment]
this is technically working now although there seems to be a SciML bug
![image](https://github.com/DARPA-ASKEM/simulation-integration/assets/14170067/9bd99316-8fdb-4776-bd70-4506af817ad2).

will open in a separate issue
