### ISSUE TITLE
TA3 Integration Tests

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/simulation-integration#3]
## Overview

This issue is to create a test running framework akin to the Knowledge Middleware test framework for TA3. Since both PyCIEMSS Service (PCS) and the SciML Simulation Service (SMSS) are standalone, it _could_ make sense for these integration tests to live here so that they can be built out separately in a single space that can be managed independently from either of those services or Terarium Data Service (TDS).  

The _challenge_ with this is that there is no simple or easy way to mock TDS responses outside those individual services. If the tests are kicked off separately here, it implies that PCS, SMSS, and TDS are all running (e.g. in prod) and that real model configurations would be created for each test run and real simulation results would be stored to prod. This may not be desirable.

If the test are run individually inside PCS and SMSS this can be mitigated via mock calls/responses to TDS but it means that both PCS and SMSS would need their own test running suite. Either way, the scenarios should live in a single location--this repo--and should include test scenarios for:

* Simulate,
* Calibrate
* OptimizeSimulate
* OptimizeCalibrate
* EnsembleSimulate
* EnsembleCalibrate

## Decision Needed

Should we:

- [x] implement a test runner suite in this repo and then (optionally) manage the created TDS artifacts (e.g. delete/clean them up) at the end of the run?
- [x] implement two test runner suites: one on PCS and one on SMSS with mocked calls to and responses from TDS?
- [x] use docker compose to run the test suite "offline" but using real images

> If we select the second option above we will need to work with the Julia team to ensure that an appropriate report is generated that maps to the report spec produced by PCS

## Next Steps

- [x] @mattprintz @fivegrant can you think a bit on the decision needed above and recommend a direction on that prior to the TA3 WG tomorrow?
- [x] NOT APPLICABLE: ~~develop a notional spec similar to KM's [`resources.yaml`](https://github.com/DARPA-ASKEM/knowledge-middleware/blob/main/tests/resources.yaml) which defines what is required to run one of the test types described above~~
- [x] develop a directory structure for test scenarios that mirror's KMs and add corresponding scenarios:
  - [ ] basic
  - [ ] relevant 12 month eval scenarios
  - [x] scenario for SIDARTHE or other petrinet models if possible
- [x] develop a TA3 report spec that can be ingested into the Integration Dashboard

**Comment by brandomr** [comment]
@fivegrant a docker compose sounds like a great option. Please discuss with @mattprintz and if that makes sense let's get going on this. I think we should also rename this repo to something like `simulation-integration` or `ta3-integration`.

**Comment by fivegrant** [comment]
Closing because this is effectively done. Opening issues for the remaining small tasks
