### ISSUE TITLE
Write PetriNet MIRA model edit tests in the integration dashboard

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/simulation-integration#59]
As part of implementing PetriNet model editing in Terarium, we should:
* create a TA2 section in the integration board 
   * https://github.com/DARPA-ASKEM/integration-dashboard
   * https://integration-dashboard.terarium.ai/TA3 
* write some unit tests based on the model-edit code snippets
   * list of operations & code snippets: https://docs.google.com/document/d/1zzh-F7QKhvzwRibpBR0KkNxZ284EaU_DuDWWBsA_SrA/edit#heading=h.gex5uyr8umh9
   * ideas: https://github.com/gyorilab/mira/blob/main/tests/test_template.py

**Comment by liunelson** [comment]
Tagging @fivegrant @brandomr for visibility.
Does this task make sense to you?

**Comment by brandomr** [comment]
Yep this makes sense to me. We _could_ put those unit tests here or put them somewhere else. I don't have strong feeling either way; we don't really have a TA2 specific repo for this type of thing.
